// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // AJUSTE REALIZADO: Agora o Linux usa as configurações da Web
        // para não dar erro durante o desenvolvimento.
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4_ejr1Ai_BHjgdYlaJ3yb8KBdzoYw014',
    appId: '1:702774061254:web:1da8ca3d3e1454920bcfc7',
    messagingSenderId: '702774061254',
    projectId: 'agrosmart-v5',
    authDomain: 'agrosmart-v5.firebaseapp.com',
    storageBucket: 'agrosmart-v5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzRMP7J3DDz0NtjratZiR0Z_3Vk0f_Xmw',
    appId: '1:702774061254:android:d30b0ff346888b0c0bcfc7',
    messagingSenderId: '702774061254',
    projectId: 'agrosmart-v5',
    storageBucket: 'agrosmart-v5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2QcJzFStdU1NfyE6D6oifyrJo7IjZUyU',
    appId: '1:702774061254:ios:7b9037fa283ccc4b0bcfc7',
    messagingSenderId: '702774061254',
    projectId: 'agrosmart-v5',
    storageBucket: 'agrosmart-v5.firebasestorage.app',
    androidClientId: '702774061254-frlg2s3718admt4g9gc2cutmko50ip3c.apps.googleusercontent.com',
    iosClientId: '702774061254-5nh6dgmurd3aj9tkl2ql952q7u9p6eck.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrosmartAppV5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2QcJzFStdU1NfyE6D6oifyrJo7IjZUyU',
    appId: '1:702774061254:ios:7b9037fa283ccc4b0bcfc7',
    messagingSenderId: '702774061254',
    projectId: 'agrosmart-v5',
    storageBucket: 'agrosmart-v5.firebasestorage.app',
    androidClientId: '702774061254-frlg2s3718admt4g9gc2cutmko50ip3c.apps.googleusercontent.com',
    iosClientId: '702774061254-5nh6dgmurd3aj9tkl2ql952q7u9p6eck.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrosmartAppV5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4_ejr1Ai_BHjgdYlaJ3yb8KBdzoYw014',
    appId: '1:702774061254:web:a298e7bd8e75b2d50bcfc7',
    messagingSenderId: '702774061254',
    projectId: 'agrosmart-v5',
    authDomain: 'agrosmart-v5.firebaseapp.com',
    storageBucket: 'agrosmart-v5.firebasestorage.app',
  );

}